spring:
  jpa:
    hibernate:
      ddl-auto: validate

csvloader:
  filepath: ${CSVLOADER_FILEPATH:dummydata/sets.csv}

dummyimageloader:
  path: ${DUMMYIMAGELOADER_PATH:dummydata/images}

html-description-loader:
  path: ${HTML_DESCRIPTION_LOADER_PATH:dummydata/html-desc}