spring:
  jpa:
    hibernate:
      ddl-auto: validate  # for dev, recreate schema on each start
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  docker:
    compose:
      enabled: false

app:
  load-demo-data: true

csvloader:
  filepath: ${CSVLOADER_FILEPATH:dummydata/sets.csv}

dummyimageloader:
  path: ${DUMMYIMAGELOADER_PATH:dummydata/images}

html-description-loader:
  path: ${HTML_DESCRIPTION_LOADER_PATH:dummydata/html-desc}

com:
  tomcvt:
    ntfy:
      priority: 1
      urgent-priority: 2